// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxdT8O3I-2Qgnt1iis58Qn28XHhDsWO8',
    appId: '1:239191849405:web:3774e66ee9f115b97efad4',
    messagingSenderId: '239191849405',
    projectId: 'mostafa-mohamed-portfolio',
    authDomain: 'mostafa-mohamed-portfolio.firebaseapp.com',
    storageBucket: 'mostafa-mohamed-portfolio.firebasestorage.app',
    measurementId: 'G-FFSC4XD7YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8B3ZQgXjMkjQVefplc4z2ZAyK3cp4kY',
    appId: '1:239191849405:android:3504ba5824a2447b7efad4',
    messagingSenderId: '239191849405',
    projectId: 'mostafa-mohamed-portfolio',
    storageBucket: 'mostafa-mohamed-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FHX8rFXf-e7LJQ4yg2vZ8-DfjYFx3KU',
    appId: '1:239191849405:ios:0e5322d53893446b7efad4',
    messagingSenderId: '239191849405',
    projectId: 'mostafa-mohamed-portfolio',
    storageBucket: 'mostafa-mohamed-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.myPrsonalPortfolio',
  );
}
